# Generated by Django 4.2.6 on 2023-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceUuid", models.CharField(max_length=100)),
                ("generatedTime", models.BigIntegerField()),
                ("value", models.FloatField()),
            ],
        ),
    ]
