# Generated by Django 4.2.6 on 2023-12-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writedata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ami",
            name="value",
            field=models.CharField(max_length=100),
        ),
    ]
