# Generated by Django 4.2.6 on 2023-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writedata", "0002_alter_ami_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ami",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
