# Generated by Django 4.2.6 on 2023-12-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writedata", "0003_alter_ami_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ami",
            name="generatedTime",
            field=models.CharField(max_length=100),
        ),
    ]
