# Generated by Django 4.2.6 on 2023-12-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writedata", "0004_alter_ami_generatedtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ami",
            name="generatedTime",
            field=models.BigIntegerField(),
        ),
    ]
